parameters:
  rodgermd.mailchimp.wrapper_class: "Rodgermd\MailchimpWrapperBundle\Wrapper\APIWrapper"

services:
  rodgermd.mailchimp:
    class: %rodgermd.mailchimp.wrapper_class%
    arguments: [%rodgermd.mailchimp.api_key%, %rodgermd.mailchimp.default_list_id%, %rodgermd.mailchimp.default_from_email%]